name: Update Data Automatically

on:
  workflow_dispatch:  # 👈 this line enables the Run button
  schedule:
    - cron: '0 * * * *'  # every hour


permissions:
  contents: write  # ✅ This line allows pushing to repo

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
               python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update: refreshed data files on $(date)"
          git push
